port: 7880
bind_addresses:
  - 0.0.0.0

rtc:
  tcp_port: 7881
  port_range_start: 40000
  port_range_end: 40100
  use_external_ip: true

redis:
  address: redis:6379

keys:
  bravo-local-livekit: 1234

turn:
  enabled: true
  domain: media.onepad.local
  cert_file: ""
  key_file: ""
  tls_port: 5349
  udp_port: 3478

webhook:
  api_key: 1234
  urls:
    - https://onepad.local/media/livekit/webhooks

logging:
  level: info
